version: '2'

services:
    flaskapp_swap:
        build: .
        ports: 
            - "2222:2222"
        image: flaskapp_swap
        container_name: flaskapp_swap
        environment:
            - VIRTUAL_HOST=flaskapp.swap.io