version: '2'

services:
    universal-sentence-encoder-docerised-service:
        build: .
        ports: 
            - "2222:2222"
        image: universal-sentence-encoder-docerised-service
        container_name: universal-sentence-encoder-docerised-service
        environment:
            - VIRTUAL_HOST=flaskapp.swap.io